version: '3.8'

networks:
  back:
    driver: bridge
    name: back
  traefik:
    driver: bridge
    name: traefik
    #external: true


services:
  
  traefik:
    image: "traefik:latest"
    container_name: traefik
    restart: unless-stopped
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--entrypoints.influx.address=:8086"
      - "--certificatesresolvers.myresolver.acme.tlschallenge=true"
      - "--certificatesresolvers.myresolver.acme.email=veikko@toast.fi"
      - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"
      - "--metrics.influxdb2=true"
    ports:
      - "8081:80"
      - "8082:8080"
      - "8443:443"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "./letsencrypt:/letsencrypt"
    networks:
      - traefik

  mysql:
    image: mariadb
    container_name: mysql
    volumes:
      - ./data/mysql:/var/lib/mysql
    env_file:
      - ./env/db.env
    restart: always
    networks:
      - back

  wordpress:
    image: wordpress:php8.1-fpm-alpine
    volumes:
      - ./data/html:/var/www/html
    depends_on:
      - mysql
    env_file:
      - ./env/wp.env
    networks:
      - back
      - traefik
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik"
      - "traefik.http.routers.wordpress.rule=Host(`localhost`)"
      - "traefik.http.routers.wordpress.entrypoints=web"

  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - ./data/html:/var/www/html
    networks:
      - traefik
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik"
      - "traefik.http.routers.wordpress.rule=Host(`localhost`)"
      - "traefik.http.routers.wordpress.entrypoints=web"
  
#volumes:
